### ISSUE TITLE
Parse error disallows ?::typecast

### ISSUE THREAD

**Issue by anmonteiro** [paurkedal/ocaml-caqti#101]
Caqti doesn't parse the following query:

```sql
WITH data(name, age) AS (
  VALUES (?::varchar, 25)
)

insert into ...
```

It errors with:

```
Fatal error: exception Failure("Parse error at byte 50: ':' is not allowed after parameter reference '?'")
```

Though e.g. Postgres should have no issue with it (e.g. a github search yields many results for this pattern https://github.com/search?q=%3F%3A%3Avarchar&type=code )

**Comment by paurkedal** [comment]
The think the only PostgreSQL syntax for unnamed parameters is `$1::varchar`. The liked code is maybe using a system which translates the `?` to `$n`, like Caqti, but without the restriction on what can follow directly after a `?`?  The error can be avoided by adding a space between the `?` and the first `:`.  The reason for the restriction is to avoid accepting something which in a future version might be interpreted, but I can be convinced to lift it.

**Comment by paurkedal** [comment]
Fixed by making an exception to the exception: `?` can now be followed by a colon if that colon is followed by another one.

**Comment by anmonteiro** [comment]
Works great after testing, thanks!
