### ISSUE TITLE
What's the difference between caqti-eio and caqti-eio.unix?

### ISSUE THREAD

**Issue by dangdennis** [paurkedal/ocaml-caqti#102]
Excuse the ignorance. But when is it okay to use just caqti-eio as opposed caqti-eio.unix? 

Couple days ago I learned I had to use the unix version instead due to some error. I forgot the exact details of why now.

**Comment by paurkedal** [comment]
The difference is that the `caqti-eio.unix` links against `eio.unix` to provide functionality required by mariadb, postgresql, and sqlite3, otherwise only `pgx` is supported.
