### ISSUE TITLE
Implement MariaDB/MySQL backend

### ISSUE THREAD

**Issue by paurkedal** [paurkedal/ocaml-caqti#2]
There are currently two MySQL client libraries for OCaml which I know about, [mysql](http://ocaml-mysql.forge.ocamlcore.org) and [mysql_protocol](https://forge.ocamlcore.org/projects/ocmysqlprotocol/). However, non of them are non-blocking.  MariaDB has a nice [non-blocking API](https://mariadb.com/kb/en/non-blocking-api-reference/), but no OCaml bindings as far as I know.

**Comment by andrenth** [comment]
FWIW, https://github.com/andrenth/ocaml-mariadb :)

**Comment by paurkedal** [comment]
Yeah, I had a quick look at it after your announcement to the ocaml list, and it seems the be precisely what I'll need.

**Comment by paurkedal** [comment]
Essential support for MariaDB added to master: 71226d0a19ef7e7a95a83d9d8bbbb9acd66dcbac.

**Comment by paurkedal** [comment]
Describe functionality was omitted from the new API for now, so MariaDB support will be complete in the upcoming release.
