### ISSUE TITLE
should be on opam

### ISSUE THREAD

**Issue by c-cube** [paurkedal/ocaml-caqti#3]
if you want people to use, or even just try, your library, it should be on opam :-)

**Comment by paurkedal** [comment]
I agree.  But it may also be good to hear if people have comments on the design, so I can do some final API changes before it gets widely used.

In the meantime it's included in my private repository, [opam-repo-paurkedal](https://github.com/paurkedal/opam-repo-paurkedal).

**Comment by paurkedal** [comment]
Caqti 0.9.0 is now in opam-repository. That took long, though the adjustments of the design and inclusion of MariaDB was good to get in place first.
