### ISSUE TITLE
How to supply a PostgreSQL notice handling function in OCaml Caqti?

### ISSUE THREAD

**Issue by vog** [paurkedal/ocaml-caqti#33]
Caqti exhibits the default behavior for handling PostgreSQL notices (see https://www.postgresql.org/docs/current/libpq-notice-processing.html).

That is, all PostgreSQL notices are **printed to stderr** when using Caqti, which is annoying.

* Is it possible to tell Caqti to provide a difference notice processing function to PostgreSQL?

* Alternatively, is it possible to suppress all notices, warnings etc. of PostgreSQL in Caqti?

*(Note: This is a copy of https://stackoverflow.com/q/60279183/19163, as I don't know which is the correct place to ask this question.)*

**Comment by paurkedal** [comment]
Good point.  I think the correct way of handling it is to reroute them to `Logs`, maybe as a dedicated source.  The postgresql library already implement `PQsetNoticeReceiver`, so it should be quick to implement.

**Comment by vog** [comment]
This sounds reasonable, but may I suggest to then mention in the Caqti docs how to disable logging for that source (or linking to a corresponding place in the Logs docs)? I don't think that Logs is widespread enough to assume safely that all Caqti users are familar with Logs.

**Comment by paurkedal** [comment]
Yes, I'll mention logs in the documentation.  It is up to the application to set it up if it wants any messages.  By default nothing is shown, so only errors will be reported (as `result`).

Though the callback only receives strings, they hopefully contain the prefixes so we can distinguish the level.  If so, I think a suitable mapping is that WARNING, NOTICE, and DETAIL goes to Warning, Info, and Debug, respectively.  That means further that with a default logs setup, one would only receive the WARNING level messages.

**Comment by vog** [comment]
That sounds great!

**Comment by paurkedal** [comment]
I'll have to back out on the "quick to implement" claim, as I hit an issue when using the notice processor in combination with async operation (mmottl/postgresql-ocaml#37), but I think we can sort that out.

**Comment by paurkedal** [comment]
I think the solution for now will be to make it possible to silence the notices and warnings, see the postgresql-ocaml issue for details.  And I think I'll make it the default.

**Comment by paurkedal** [comment]
The Caqti driver for PostgreSQL now ([commit](https://github.com/paurkedal/ocaml-caqti/commit/e54b680bf8ddf520dc9491d4069e3d97c47f41c5)) accepts an URI parameter `notice_processing` which can be used to choose whether or not to send notices to standard error, with default of not doing so. I'll make a release soon.
