### ISSUE TITLE
Does the sqlite3 driver cache prepared statements?

### ISSUE THREAD

**Issue by dgllghr** [paurkedal/ocaml-caqti#35]
Great project! It provides just the right level of abstraction over the low level ocaml-sqlite3 library.

In the README it says that the sqlite3 driver does not cache prepared statements. However, I took a quick glance through the code and it does look like it is caching prepared statements (in the `pcache` Hashtbl).

Since caching prepared statements is a bonus, I'd be happy to update the README so that it correctly advertises this feature. But I wanted to check first to make sure I am interpreting the code correctly.

**Comment by paurkedal** [comment]
You are right, thanks for reporting it.  Since the change was minimal, I committed it myself, hope you don't mind.

**Comment by dgllghr** [comment]
No I appreciate it. Thanks for making the change!
