### ISSUE TITLE
What is the best way to define arbitrary tuple sizes?

### ISSUE THREAD

**Issue by xguerin** [paurkedal/ocaml-caqti#36]
`Std` defines up to `tup4`. What is the best approach to define longer tuples? Using `custom`?

**Comment by paurkedal** [comment]
It is possible to define tuples of tuples.  I usually group related columns into subtuples, but a more systematic approach would be to only use `tup2`, maybe adding a custom binary operator.  I don't advice using `custom` for common cases, it's easier to stick to tuples.

**Comment by xguerin** [comment]
Awesome, makes sense. Thanks !

**Comment by mooreryan** [comment]
Is there a technical reason not to support tuples larger than 4 directly?  Chaining `tup2 string (tup2 string (tup2 string ...` when you have to work a lot of values/columns in a request/response doesn't feel so nice.  (Of course, what feels nice is subjective.)
