### ISSUE TITLE
Transactions?

### ISSUE THREAD

**Issue by xguerin** [paurkedal/ocaml-caqti#37]
The README mentions supports for transactions. I perused the interface but did not see any function related to transactions. Is it as simple as framing multiple `exec` with `exec "BEGIN"` and `exec "COMMIT"` ?

**Comment by paurkedal** [comment]
The connections modules have dedicated functions [start][], [commit][], and [rollback][] for dealing with transactions.  (Your approach would work though, at least for PostgreSQL and Sqlite3 where this is precisely how the functions are implemented.)

[start]: https://paurkedal.github.io/ocaml-caqti/caqti/Caqti_connection_sig/module-type-S/index.html#val-start
[commit]: https://paurkedal.github.io/ocaml-caqti/caqti/Caqti_connection_sig/module-type-S/index.html#val-commit
[rollback]: https://paurkedal.github.io/ocaml-caqti/caqti/Caqti_connection_sig/module-type-S/index.html#val-rollback

**Comment by xguerin** [comment]
Thanks for your answer. I does, indeed work quite well. I'll take a look at those functions. Sorry for not finding them, I must have been one coffee short of the right amount when I perused the doc :)
