### ISSUE TITLE
Can UPDATE and INSERT return the result type instead of unit?

### ISSUE THREAD

**Issue by cironunes** [paurkedal/ocaml-caqti#44]
When doing `Caqti_lwt.Pool.use(create', pool)`, would it make sense to return the result instead of `unit`?

My use case is that I have a GraphQL mutation that creates one register in Postgres. I need to take it back and return it through my resolver function. I thought I could use the return of my `create` function to get the created user with id and return it, but it turns out its unit.

**Comment by cironunes** [comment]
Got it going with `RETURNING` and `get_one`

**Comment by paurkedal** [comment]
Good you found a solution.  I also find `RETURNING` very useful (though I didn't quit understand your specific case).

**Comment by cironunes** [comment]
I needed to get back the `id` or the created record, but I wasn't `RETURNING` it :)

**Comment by vyorkin** [comment]
Would you mind sharing a short example?

The following doesn't work:

```ocaml
  let create todo =
    let open todo in
    [%rapper get_one
        {sql|
        insert into todo.todos(content)
        values (%string{content})
        returning id
        |sql}
        record_in
        function_out
    ]
    (fun ~id -> { todo with id = some id } )
    todo
```

Error:
```
dune build
File "lib_db/todo.ml", lines 27-35, characters 4-5:
27 | ....[%rapper get_one
28 |         {sql|
29 |         INSERT INTO todo.todos(content)
30 |         VALUES (%string{content})
31 |         RETURNING id
32 |         |sql}
33 |         record_in
34 |         function_out
35 |     ]
Error: broken invariant in parsetree: Tuples must have at least 2 components.
Done: 225/236 (jobs: 1)make: *** [Makefile:4: default] Error 1
```

**Comment by paurkedal** [comment]
This must be related to [`ppx_rapper`](https://github.com/roddyyaga/ppx_rapper), though I haven't familiarized myself with it yet, so I can't say where the bug is.

**Comment by paurkedal** [comment]
@vyorkin I think you forgot to tag the returned field, the following compiles:
```ocaml
type todo = {
  id: int option;
  content: string;
} [@@deriving show]

let create todo =
  [%rapper get_one
    {sql|
      INSERT INTO todo.todos(content)
      VALUES (%string{content})
      RETURNING @int{id}
    |sql}
    record_in function_out]
  (fun ~id -> {todo with id = Some id})
  todo
  [@@warning "-9"]
```

**Comment by vyorkin** [comment]
You're right, thanks!
