### ISSUE TITLE
Drop ppx_deriving

### ISSUE THREAD

**Issue by ulrikstrid** [paurkedal/ocaml-caqti#49]
ppx_deriving is currently blocking me from compiling a project statically.

Is it used for something other than deriving.eq?

https://github.com/ocaml-ppx/ppx_deriving/issues/212

**Comment by paurkedal** [comment]
As you could see there isn't much depending on it at the moment, but I'm wondering: Why does using `ppx_deriving` prevent static compilation? The corresponding runtime library is available as a static library (`ppx_deriving_eq.a`).

**Comment by ulrikstrid** [comment]
You can see more info in the linked issue above. But basically the musl compiler can't handle the dynamic loading which you need for the plugin model of ppx_deriving.

**Comment by paurkedal** [comment]
I see. That's unfortunate, but easy to avoid for now as you can see.
