### ISSUE TITLE
The example program (bikereg.ml) crashes on my setup

### ISSUE THREAD

**Issue by Armael** [paurkedal/ocaml-caqti#5]
I installed caqti and its dependencies using the additional opam repo `https://github.com/paurkedal/opam-repo-paurkedal.git`. After compiling `examples/bikereg.ml` and running it, it fails with:

    Fatal error: exception Caqti_plugin.Plugin_invalid("caqti.caqtus-sqlite3", "Failed to link plugin: error loading shared library: /home/armael/.opam/4.04.0/lib/caqti/caqtus-sqlite3.cmxa: invalid ELF header")

Am I doing something wrong?

P.S: episql and caqti look very very nice. Thank you for these!

**Comment by paurkedal** [comment]
That's a bug. I modernised the `META` without updating the code which loads plugins. I just pushed a fix to the master branch, and will make a new release. Thanks for reporting!

**Comment by Armael** [comment]
Thanks for the quick fix! I can confirm it now works.
