### ISSUE TITLE
Queries to make on new connection

### ISSUE THREAD

**Issue by reynir** [paurkedal/ocaml-caqti#59]
I am using the sqlite3 backend, and I would like to set enforcement of foreign key constraints. This needs to be done on [every connection](https://sqlite.org/pragma.html#pragma_foreign_keys). What's the best way to go around this? I think it's not super obvious what's the best way to go around this, especially when using a pool.

**Comment by paurkedal** [comment]
I just added a `?post_connect` parameter to `connect_pool` (6b253ff) this weekend, maybe that's what you need?

**Comment by reynir** [comment]
Yes! That's perfect. Thanks!
