### ISSUE TITLE
Enum support potentially broken with latest version (1.4.0)

### ISSUE THREAD

**Issue by cvauclair** [paurkedal/ocaml-caqti#64]
Hi there! I am a big fan of the project and I was using it happily until recently. 

My database currently contains tables with a custom "enum" variable which I was able to manipulate using `Caqti_type.string` values until the latest update. Below is a toy example to illustrate my situation:

Database:
```sql
CREATE TYPE color_t AS ENUM ('RED', 'GREEN', 'BLUE');

CREATE TABLE items (
  id           SERIAL PRIMARY KEY,
  name         TEXT NOT NULL,
  color        color_t NOT NULL
);
```
Code
```reason
module Item = {
  type t = {
    id: Int32.t,
    name: string,
    color: [`RED | `GREEN | `BLUE]
  };

  let color_of_string = (fun | "RED" => Some(`RED) | "GREEN" => Some(`GREEN) | "BLUE" => Some(`BLUE) | _ => None);
  let string_of_color = (fun | `RED => "RED" | `GREEN => "GREEN" | `BLUE => "BLUE");

  let db_t = {
    let rep = Caqti_type.(tup3(int32, string, string));
    let encode = ({id, name, color}) => Ok((id, name, string_of_color(color)));
    let decode = ((id, name, color)) => {
      color_of_string(color)
      |> (fun | Some(color) => Ok({id, name, color}) | None => Error(Format.sprintf("Unknown color %s", color)))
    };
    Caqti_type.custom(~encode, ~decode, rep)
  };

  let add = ((module C: Caqti_lwt.CONNECTION), name, color) => {
    let qs = "INSERT INTO items(name, color) VALUES (?, ?) RETURNING *";
    let query = Caqti_request.find(Caqti_type.(tup2(string, string)), db_t, qs);
    C.find(query, (name, string_of_color(color)));
  };

  let get = ((module C: Caqti_lwt.CONNECTION), id) => {
    let qs = "SELECT * FROM items WHERE id = ?";
    let query = Caqti_request.find(Caqti_type.int32, db_t, qs);
    C.find_opt(query, id);
  };
};
```

Before the latest update, the above code was able to add and get items from my table without any problem, however, since recently, the `add` function returns the following error:
```
id: 1, name: potato, color: GREEN
[ERROR] Request to <postgresql://testuser:_@localhost/caqtitest> failed: ERROR:  column "color" is of type color_t but expression is of type text
LINE 1: INSERT INTO items(name, color) VALUES ($1, $2) RETURNING *
                                                   ^
HINT:  You will need to rewrite or cast the expression.
. Query: "INSERT INTO items(name, color) VALUES ($1, $2) RETURNING *".
```
(Note: the `get` function still works fine).

It is unclear to me how to fix this error since everything was working fine with Caqti version 1.3.0. I am using PostgreSQL version 13.2 and Caqti version 1.4.0 on Arch Linux. Downgrading to 1.3.0 solves the issue but I like to keep my packages up to date. Any help appreciated. 

Thanks for the help and the awesome library!

**Comment by paurkedal** [comment]
This was broken by the passing of parameter types to PostgreSQL, or rather enums have worked accidentally before that addition.  I think the best option is to add enum support to the Caqti types, but before I do, I'd like to understand the the issue with smallint, which I referred by to this issue, as you can see just above this post.

**Comment by paurkedal** [comment]
This should hopefully hit OPAM soon as version 1.5.0.
