### ISSUE TITLE
Caqti_lwt.Pool.use does not release connections on Lwt promise rejection

### ISSUE THREAD

**Issue by aantron** [paurkedal/ocaml-caqti#68]
This can be observed in the following program, which acquires a connection from the pool (I beleive, of size 1 for SQLite), and then immediately rejects an Lwt promise. Once that is done, it tries to acquire a connection again, but never proceeds to do so.

```ocaml
let run_query pool =
  pool
  |> Caqti_lwt.Pool.use (fun _db ->
    prerr_endline "acquired a connection";
    Lwt.fail Exit)

let () =
  Lwt_main.run begin
    let uri = Uri.of_string "sqlite3:db.sqlite" in
    let pool = Caqti_lwt.connect_pool uri |> Result.get_ok in

    Lwt.on_termination
      (run_query pool)
      (fun () -> run_query pool |> ignore);

    Lwt_unix.sleep 1.
  end
```

The program prints `"acquired a connection"` only once, but it should print twice.

Changing `Lwt.fail Exit` to `raise Exit` or `Lwt.return (Ok ())` causes it to print `"acquired a connection"` twice.

This is probably because

https://github.com/paurkedal/ocaml-caqti/blob/06242515a50e2e413b7958ae09acf3aa1381de68/lib/caqti_pool.ml#L116-L124

handles nested result cases and immediate exceptions, but not promise rejections. It probably can't readily handle promise rejections, because it is defined for a generic promise monad that is assumed not to reject.

A correct Lwt version of `use` would probably use `Lwt.finalize` to handle all cases in a concise manner. Perhaps a `finally` should be added to `Caqti_sql_io.MONAD`?

**Comment by paurkedal** [comment]
Yes, this is a good idea. The though of the original design was not to only support result and threat anything else a bugs, but that's an unnecessary discipline to impose, esp. when it's so easy to fix.

**Comment by aantron** [comment]
Thanks! https://github.com/paurkedal/ocaml-caqti/commit/cacf417e908ebbae91dededee6034e611890d8df looks good for handling rejections, but I suspect it no longer handles `Error _`.

**Comment by paurkedal** [comment]
But is there anything to handle?  We just need to pass the result across the `release` call, i.e. the original code
```ocaml
(function
 | Ok y -> release p e >|= fun () -> Ok y
 | Error err -> release p e >|= fun () -> Error err)
```
is really just `fun r -> release p e >|= fun () -> r`.

**Comment by aantron** [comment]
Ah yes, that's right. I was staring at the code and being too literal about its translation.
