### ISSUE TITLE
Caqti_request.find_opt : different error-behavior between sqlite and postgresql

### ISSUE THREAD

**Issue by smondet** [paurkedal/ocaml-caqti#69]
When the `find_opt` is used with a `SELECT ... WHERE ..` that returns more than one value, the Sqlite3 backend seems to return the first value it finds, while the postgresql backend fails with

```
        Database-error: Unexpected result from
        <postgresql://postgres:_@localhost:5432/postgres>: Received 2 tuples,
```

(I do prefer the PostgreSQL behavior :) which is the "production" backend in my use-case)

**Comment by paurkedal** [comment]
Yes, that's the intended behaviour. Fixed.
