### ISSUE TITLE
Crashes with invalid plugin error

### ISSUE THREAD

**Issue by sgrove** [paurkedal/ocaml-caqti#7]
I'm not sure what to make of this - it compiles, but looks like when loading the plugin because of the uri it fails with this message. I have postgres installed and working just fine from jdbc, so I'm not sure which shared lib it's trying to find.

```
./server.native
Fatal error: exception Caqti_plugin.Plugin_invalid("caqti.caqtus-postgresql", "Failed to link plugin: error loading shared library: dlopen(<dir>/lib/caqti/caqtus-postgresql.cmxa, 138): no suitable image found.  Did find:\n\t<dir>/lib/caqti/caqtus-postgresql.cmxa: file too short")
```

**Comment by paurkedal** [comment]
This may be a bug in `Caqti_plugin.findlib_load`. There seems to be a `<dir>` component in the result from `Findlib.package_directory` which it should probably have expanded. I'll have a closer, but it may take a few days, as I'm currently at a busy conference.

**Comment by paurkedal** [comment]
I forgot to mention that there is a workaround.  You can link against the `caqti.caqtus-postgresql` findlib library and add the `-linkall` flag (or make a explicit reference to the module) to enable the postgresql backend without dynamic linking.

**Comment by paurkedal** [comment]
I think dynamic loading of backends is more solid now.  In particular I added the `-linkall` option and let the findlib library do most of the work in loading the libraries. The new version is 0.6.0 and is available in `git@github.com:paurkedal/opam-repo-paurkedal.git`.

Note that package are now split up according to dependencies (to avoid misusing depopts), so one would e.g. install `caqti`, `caqti-lwt` and `caqti-driver-postgresql` to use the PostgreSQL driver with Lwt, but you still only need to link against the former two, as the latter gets loaded dynamically.
