### ISSUE TITLE
is there a way to cancel a query?

### ISSUE THREAD

**Issue by pw374** [paurkedal/ocaml-caqti#74]
Say there's a query that's taking too much time, and I want to kill it so that I can reuse that connection for other queries. Is it possible?

I thought naively that Lwt.cancel could do the job but it doesn't work and I end up with `Invalid concurrent usage of PostgreSQL connection detected.`

**Comment by paurkedal** [comment]
I will take a look whether `Lwt.cancel` can be supported, but some options for the current version may be to set [`statement_timeout`](https://www.postgresql.org/docs/13/runtime-config-client.html) on the connection before issuing the long-running statements.

**Comment by pw374** [comment]
> I will take a look whether `Lwt.cancel` can be supported, but some options for the current version may be to set [`statement_timeout`](https://www.postgresql.org/docs/13/runtime-config-client.html) on the connection before issuing the long-running statements.

I think that trick do for now. Thanks!

**Comment by pw374** [comment]
Thank you! 😊
