### ISSUE TITLE
sqlite3 driver: assertion fails for queries with optional argument

### ISSUE THREAD

**Issue by reynir** [paurkedal/ocaml-caqti#78]
The below assertion can fail and #77 contains a case for reproducing this assertion failure.
https://github.com/paurkedal/ocaml-caqti/blob/46ffb8f840875da5ef67df51063443ff6ad2d2c1/caqti-driver-sqlite3/lib/caqti_driver_sqlite3.ml#L476

**Comment by paurkedal** [comment]
Yes, this and two other cases were fixed by 6fd7be2fa4537f7ee8f990cbe43c0134cef2807b. Thanks.
