### ISSUE TITLE
Setting Busy timeout for Sqlite3 Connections

### ISSUE THREAD

**Issue by Gopiandcode** [paurkedal/ocaml-caqti#93]
I'm using Caqti for a project using Sqlite3, but I've been running into BUSY errors when calling the API. After asking on the OCaml discuss, I've been suggested to configure the Sqlite connection using the `sqlite3_busy_timeout` function (defined [here](https://sqlite.org/matrix/c3ref/busy_timeout.html)), however, this doesn't seem to be exposed via the Caqti API, and I can't easily get access to the underlying DB connection.

Would it be possible to add this function to the Caqti API somehow?

**Comment by Gopiandcode** [comment]
Might be related to #56 , or could be solved by a bespoke function.

**Comment by paurkedal** [comment]
Yes, a solution to #56 would be to make the underlying connection object available.  This can be done for sqlite3 and postgresql, but not (at least the way I imagined) for mariadb.  As a more high-level solution, I am currently looking into #89.

**Comment by paurkedal** [comment]
I think there is a more immediate solution to this.  [`PRAGMA busy_timeout`](https://sqlite.org/pragma.html#pragma_busy_timeout) is an SQL variant of the C function.  For the connections derived from the pool, I suggest setting it in the `?post_connect` callback of `create_pool`.  Note that it does not work with parameters and it seems to return a row with the value of the busy parameter just set, so the Caqti type should be `unit -->! int`.

**Comment by Gopiandcode** [comment]
Ah, yes, perfect! Thanks for the prompt response - you're right, for this, I guess I can just send a `PRAGMA busy_timeout` for this situation. Thanks again for your hard work on maintaining this library.
