### ISSUE TITLE
Failure to connect with Cockroach serverless uri

### ISSUE THREAD

**Issue by dangdennis** [paurkedal/ocaml-caqti#95]
## Issue

Caqti cannot connect to cockroachdb serverless's uri. I suspect it might be that a particular query param is filtered out during uri parsing.

## Example

Attempting to connect to cockroach's url at `postgresql://user:password@free-tier14.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster=some-cluster-name-4321` yields

```
18.09.22 21:27:43.110       dream.log  WARN Called from Caqti_driver_postgresql.Connect_functor.connect.(fun) in file "caqti-driver-postgresql/lib/caqti_driver_postg1
18.09.22 21:27:43.110      dream.http ERROR REQ 4 Failed to connect to <postgresql://dennis:_@free-tier14.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=v"

18.09.22 21:27:43.110      dream.http ERROR REQ 4 Raised at Stdlib__Map.Make.find in file "map.ml", line 137, characters 10-25
18.09.22 21:27:43.110      dream.http ERROR REQ 4 Called from Logs.Tag.find in file "src/logs.ml", line 154, characters 14-32
```

Notice that `<postgresql://dennis:_@free-tier14.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=v"` misses the expected `&options=--cluster=some-cluster-name-4321`. 

Anyone can create a new cluster for free at https://cockroachlabs.cloud/

If I resolve the issue, I'll create a PR

**Comment by dangdennis** [comment]
```
Failed to connect to <postgresql://dennis:_@free-tier14.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster=saucy-gundi-4894>: Connection failure: extra key/value separator "=" in URI query parameter: "options"
```

**Comment by paurkedal** [comment]
Are you sure the option and argument shall be separated by a `=` and note a space (`%20`)?  As for as I can tell, the error comes from either libpq or the remote side, since Caqti passes the URI to ocaml-postgresql which passes it to libpq.

**Comment by paurkedal** [comment]
Can you check if 867049eeb56d1d63d3c06823f781907f9167cf60 (on master) fixes the issue?

**Comment by dangdennis** [comment]
I'll check this out today. Thank you for the commit @paurkedal. Can you explain how you locally iterate on the ocaml library? I couldn't figure out the workflow.

My best attempt was to use opam to pin caqti and caqti-driver-postgresql to the local clone of this repo such that my app would be use the locally pinned repo with my changes. That didn't work.

I also couldn't understand why the caqti-driver-postgresql tests to yield anything test results with `dune runtest caqti-driver-postgresql -f` beyond 

```
Testing `test_postgresql'.
This run has ID `W3JIEGJ5'.


Full test results in `~/Desktop/ocaml-caqti/_build/default/caqti-driver-postgresql/test/_build/_tests/test_postgresql'.
Test Successful in 0.000s. 0 test run.
```

**Comment by paurkedal** [comment]
To your first question, `opam pin add caqti-driver-postgresql --dev-repo` should work, since it's still compatible with the released packages.  In general, you might have to pin all Caqti packages you use.

To the second question, the testsuite will only test against URIs listed in the file `testsuite/uris.conf`, which defaults to sqlite3-only. Put one URI per line.

**Comment by dangdennis** [comment]
It works! I connected to my serverless crdb cluster and successfully queried some data.
