### ISSUE TITLE
ppx_rapper presentation limited to PostgreSQL

### ISSUE THREAD

**Issue by F-Loyer** [paurkedal/ocaml-caqti#98]
In the README.md, there is

[ppx_rapper](https://github.com/roddyyaga/ppx_rapper) - a syntax extension for Caqti/PostgreSQL queries

However, ppx_rapper works very well with MySQL/MariaDB or SQLite. Then we could simply write

[ppx_rapper](https://github.com/roddyyaga/ppx_rapper) - a syntax extension for Caqti queries. It simplify the type specification of queries.

**Comment by paurkedal** [comment]
Thanks!
