### ISSUE TITLE
Is Caqti_type.Std.custom still unstable?

### ISSUE THREAD

**Issue by mooreryan** [paurkedal/ocaml-caqti#99]
In the mli docs, there is a [note](https://github.com/paurkedal/ocaml-caqti/blame/f3a739d640bec44cc10176692ace3a8764aedabe/caqti/lib/caqti_type_sig.mli#L66) that says that this function "should be considered experimental and may be revised or removed in a future version".  I checked the git blame and that warning has been in the docs for ~5 years, so can we assume that it is no longer unstable?   Also, I the [2.0.0](https://github.com/paurkedal/ocaml-caqti/issues/90) issue didn't mention anything about it, so just wanted to check.

([Related issue](https://github.com/paurkedal/ocaml-caqti/issues/4#issuecomment-336709195))

**Comment by paurkedal** [comment]
You are right. It has been around for a long time without a need for reversion, and people are using it anyway.
